server:
  port: 30000
  servlet:
    session:
      timeout: 1d

app:
  base-url: http://authlab.test:30000
  allowed-origins: http://localhost:5173,http://authlab.test:5173
  frontend-base-url: http://authlab.test:5173
  par-demo:
    client-id: spa-par-client
    client-secret: par-secret

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ssdemo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Hu1992825!Xyz!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
       # mode: never
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.security: DEBUG
    com.demo.authserver: DEBUG
